description=Adds a ?flatten query flag to mapping read endpoints to return field paths in dot-notation.
version=${project.version}
name=${plugin.name}
classname=${plugin.classname}
java.version=21
elasticsearch.version=${es.version}
